name: Check Shell Scripts

on:
  push:
    paths:
      - 'subcommands/*.sh'
      - '.github/workflows/check-shell.yml'
  pull_request:
    paths:
      - 'subcommands/*.sh'
      - '.github/workflows/check-shell.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install mise and setup
        uses: jdx/mise-action@v3
        with:
          install: true
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format
        run: task sh:fmt

      - name: Commit and Push
        uses: 23prime/simple-commit-and-push@v1
        with:
          commit-message: "Auto fix code by `task sh:fmt`"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        run: task sh:check
